using System;
using System.Collections.Generic;

namespace EconomicGame.Services
{
    /// <summary>
    /// UI language. English is the default for a broader audience;
    /// Russian is available as a toggle.
    /// </summary>
    public enum Language
    {
        En,
        Ru
    }

    /// <summary>
    /// Per-circuit (Scoped) language state. Components subscribe to
    /// <see cref="OnLanguageChanged"/> and re-render when the user flips
    /// the toggle. Persisted in a browser cookie by LanguageToggle.razor.
    /// </summary>
    public class LocalizationService
    {
        private Language _current = Language.En;

        public Language CurrentLanguage
        {
            get => _current;
            set
            {
                if (_current == value) return;
                _current = value;
                OnLanguageChanged?.Invoke();
            }
        }

        public event Action? OnLanguageChanged;

        /// <summary>
        /// Translate a key to the current language. If the key is missing
        /// from the dictionary, returns <paramref name="fallback"/> (or
        /// the key itself if no fallback given). This means newly-added
        /// UI strings that haven't been localized yet never blank out.
        /// </summary>
        public string T(string key, string? fallback = null)
        {
            if (Translations.Map.TryGetValue(key, out var pair))
            {
                return _current == Language.Ru ? pair.Ru : pair.En;
            }
            return fallback ?? key;
        }

        /// <summary>
        /// Shorthand indexer — `@Loc["home.welcome"]` in Razor.
        /// </summary>
        public string this[string key] => T(key);

        /// <summary>
        /// Localize a game ENTITY name (housing, vehicles, warehouses, factories,
        /// recipes, poker tables...). Entity names are stored in Russian inside game
        /// objects and saves (they are effectively data keys); this maps them to
        /// English for display when the UI language is English. Unknown names pass
        /// through unchanged, so nothing ever blanks out.
        /// Usage in Razor: @Loc.Entity(property.Name)
        /// </summary>
        public string Entity(string name)
        {
            if (_current == Language.Ru || string.IsNullOrEmpty(name)) return name;
            return Translations.EntityNames.TryGetValue(name, out var en) ? en : name;
        }
    }

    /// <summary>
    /// All localized strings live here as (English, Russian) pairs.
    /// Add a new entry: just append to the dictionary.
    /// Keys are namespaced with "." separators for grep-ability
    /// (e.g., "nav.market", "home.welcome").
    /// </summary>
    public static class Translations
    {
        /// <summary>
        /// Russian entity names (stored in game objects/saves as data keys) → English display names.
        /// Used by LocalizationService.Entity().
        /// </summary>
        public static readonly IReadOnlyDictionary<string, string> EntityNames =
            new Dictionary<string, string>
            {
                // Housing
                ["Маленькая комната"] = "Small Room",
                ["Квартира"] = "Apartment",
                ["Дом"] = "House",
                ["Особняк"] = "Mansion",
                // Vehicles
                ["Легковая"] = "Car",
                ["Фургон"] = "Van",
                ["Грузовик"] = "Truck",
                ["Фура"] = "Semi-Truck",
                // Land
                ["Маленький участок"] = "Small Plot",
                ["Средний участок"] = "Medium Plot",
                ["Большой участок"] = "Large Plot",
                // Warehouses
                ["Мини-склад"] = "Mini Warehouse",
                ["Склад"] = "Warehouse",
                ["Большой склад"] = "Large Warehouse",
                ["Промышленный комплекс"] = "Industrial Complex",
                ["Торговый хаб"] = "Trade Hub",
                // Factories & plantations
                ["Сахарный завод"] = "Sugar Refinery",
                ["Сталелитейный цех"] = "Steel Mill",
                ["Химический завод"] = "Chemical Plant",
                ["Текстильная фабрика"] = "Textile Mill",
                ["Фармацевтическая лаборатория"] = "Pharmaceutical Lab",
                ["Плантация тростника"] = "Sugar Cane Plantation",
                ["Кофейная плантация"] = "Coffee Plantation",
                ["Пшеничная ферма"] = "Wheat Farm",
                // Production recipes
                ["Хлеб"] = "Bread",
                ["Оборудование"] = "Machinery",
                ["Электроника"] = "Electronics",
                ["Биотопливо"] = "Biofuel",
                ["Сахар"] = "Sugar",
                ["Кофе"] = "Coffee",
                ["Химикаты"] = "Chemicals",
                ["Фармацевтика"] = "Pharmaceuticals",
                ["Люкс-товары"] = "Luxury Goods",
                ["Текстиль"] = "Textiles",
                // Poker tables
                ["Задняя комната"] = "Back Room",
                ["Покерный клуб"] = "Poker Club",
                ["Хайроллеры"] = "High Rollers",
            };

        public static readonly IReadOnlyDictionary<string, (string En, string Ru)> Map =
            new Dictionary<string, (string, string)>
        {
            // ----- Brand / chrome -----
            ["app.title"]             = ("Trader", "Trader"),
            ["app.about"]             = ("About", "О проекте"),
            ["app.language"]          = ("Language", "Язык"),

            // ----- Navigation -----
            ["nav.market"]            = ("Dashboard", "Кабинет"),
            ["nav.stock_exchange"]    = ("Exchange", "Биржа"),
            ["nav.stock_market"]      = ("📊 Stocks", "📊 Фонд. рынок"),
            ["nav.trade_listings"]    = ("Trade Listings", "Объявления"),
            ["nav.bank"]              = ("Bank", "Банк"),
            ["nav.housing"]           = ("🏠 Housing", "🏠 Жильё"),
            ["nav.logistics"]         = ("🚛 Logistics", "🚛 Логистика"),
            ["nav.production"]        = ("🏭 Production", "🏭 Производство"),
            ["nav.inventory"]         = ("📦 Inventory", "📦 Инвентарь"),
            ["nav.bar"]               = ("🍺 Bar", "🍺 Бар"),
            ["nav.poker"]             = ("🃏 Poker", "🃏 Покер"),
            ["nav.events"]            = ("🎲 Events", "🎲 События"),
            ["nav.scenarios"]         = ("🎯 Scenarios", "🎯 Сценарии"),
            ["nav.save"]              = ("💾 Save", "💾 Сохранение"),
            ["nav.ai_traders"]        = ("AI Traders", "AI-трейдеры"),
            ["nav.profile"]           = ("Profile", "Профиль"),

            // ----- Home screen -----
            ["home.welcome"]          = ("Welcome to Trader!", "Добро пожаловать в Trader!"),
            ["home.day"]              = ("Day", "День"),
            ["home.enter_name"]       = ("Enter Your Name", "Введите имя"),
            ["home.player_name"]      = ("Player name", "Имя игрока"),
            ["home.start_playing"]    = ("Start Playing", "Начать игру"),
            ["home.player"]           = ("Player", "Игрок"),
            ["home.money"]            = ("Money", "Деньги"),
            ["home.industrial_power"] = ("Industrial Power", "Промышленная мощь"),
            ["home.factories"]        = ("Factories", "заводов"),
            ["home.no_news"]          = ("No news yet…", "Новостей пока нет…"),
            ["home.threat"]           = ("Threat", "Угроза"),
            ["home.rivals"]           = ("Rivals", "Соперники"),
            ["home.coalition"]        = ("AI Coalition", "Коалиция AI"),
            ["home.coalition_bots"]   = ("bots coordinating", "ботов координируются"),
            ["home.select_section"]   = ("Select a section from the left menu.", "Выбери раздел в меню слева."),
            ["home.market_activity"]  = ("Market Activity", "Активность рынка"),
            ["home.ops_blocked"]      = ("🚨 YOUR OPERATIONS ARE BLOCKED!", "🚨 ВАШИ ОПЕРАЦИИ ЗАБЛОКИРОВАНЫ!"),
            ["home.ops_blocked_desc"] = ("Competitors have sabotaged you. Trading and production are paused.", "Конкуренты совершили саботаж. Торговля и производство временно остановлены."),
            ["home.ops_recovery"]     = ("Expected recovery", "Ожидаемое восстановление"),
            ["home.ai_escalation"]    = ("AI Escalation", "Уровень угрозы AI"),

            // ----- Dashboard / Overview screen -----
            ["dashboard.title"]             = ("Business Dashboard", "Панель управления"),
            ["dashboard.net_worth"]         = ("Total Net Worth", "Чистые активы"),
            ["dashboard.net_worth_desc"]    = ("Market value of all cash, bank savings, inventory, warehouses, vehicles, land, and factories.", "Рыночная оценка наличных, вкладов, инвентаря, складов, транспорта, земли и заводов."),
            ["dashboard.reputation"]        = ("Reputation & License", "Репутация и лицензия"),
            ["dashboard.license_level"]     = ("License Level", "Уровень лицензии"),
            ["dashboard.cargo_logistics"]    = ("Logistics & Cargo", "Склад и логистика"),
            ["dashboard.cargo_capacity"]     = ("Capacity Used", "Используемый объем"),
            ["dashboard.trading_perf"]      = ("Trading Success Rate", "Успешность сделок"),
            ["dashboard.trades_profitable"]  = ("{0} of {1} trades profitable", "{0} из {1} сделок прибыльны"),
            ["dashboard.assets_breakdown"]   = ("Asset Breakdown", "Детализация активов"),
            ["dashboard.liquid_capital"]     = ("Liquid Capital", "Ликвидный капитал"),
            ["dashboard.cash_balance"]       = ("Cash Balance", "Наличные средства"),
            ["dashboard.bank_savings"]       = ("Bank Savings", "Сбережения в банке"),
            ["dashboard.property_industry"]  = ("Property & Industry", "Недвижимость и производство"),
            ["dashboard.factories_owned"]    = ("Factories Owned", "Владение заводами"),
            ["dashboard.warehouses_owned"]   = ("Warehouses Owned", "Владение складами"),
            ["dashboard.residential_prop"]   = ("Residential Property", "Жилая недвижимость"),
            ["dashboard.land_plots"]         = ("Land Plots", "Земельные участки"),
            ["dashboard.no_housing"]         = ("Homeless / None", "Отсутствует"),
            ["dashboard.no_land"]            = ("No land owned", "Нет участков"),
            ["dashboard.vehicles_logistics"] = ("Vehicles & Transport", "Транспорт и логистика"),
            ["dashboard.no_vehicle"]         = ("You do not own a vehicle yet.", "У вас пока нет транспортного средства."),
            ["dashboard.need_vehicle"]       = ("A vehicle is required to travel and trade in financial markets.", "Транспорт необходим для перемещений и торговли на финансовых рынках."),
            ["dashboard.buy_basic_car"]      = ("Buy Basic Car", "Купить базовое авто"),
            ["dashboard.manage_logistics"]   = ("Upgrade Logistics", "Улучшить логистику"),
            ["dashboard.operational"]        = ("Operational", "Исправен"),
            ["dashboard.damaged"]            = ("Damaged", "Поврежден"),
            ["dashboard.rep_novice"]         = ("Novice", "Новичок"),
            ["dashboard.rep_associate"]      = ("Associate", "Компаньон"),
            ["dashboard.rep_partner"]        = ("Partner", "Партнёр"),
            ["dashboard.rep_magnate"]        = ("Tycoon", "Магнат"),

            // AI escalation labels
            ["escalation.neutral"]    = ("🟢 NEUTRAL", "🟢 НЕЙТРАЛЬНЫЙ"),
            ["escalation.competitive"] = ("🟡 COMPETITIVE", "🟡 КОНКУРЕНТНЫЙ"),
            ["escalation.aggressive"] = ("🟠 AGGRESSIVE", "🟠 АГРЕССИВНЫЙ"),
            ["escalation.hostile"]    = ("🔴 HOSTILE", "🔴 ВРАЖДЕБНЫЙ"),

            // ----- Inventory / dashboard cards -----
            ["inv.inventory"]         = ("📦 Inventory", "📦 Инвентарь"),
            ["inv.used"]              = ("Used", "Использовано"),
            ["inv.free"]              = ("Free", "Свободно"),
            ["inv.units"]             = ("units", "ед."),
            ["inv.stock_value"]       = ("Stock value", "Стоимость запасов"),
            ["inv.positions"]         = ("Positions", "Позиций"),
            ["inv.unique_items"]      = ("unique items", "уникальных товаров"),
            ["inv.raw_materials"]     = ("⛏ Raw Materials", "⛏ Сырьё"),
            ["inv.products"]          = ("🏭 Products", "🏭 Продукция"),
            ["inv.item"]              = ("Item", "Товар"),
            ["inv.qty"]               = ("Qty", "Кол-во"),
            ["inv.avg_price"]         = ("Avg price", "Ср. цена"),
            ["inv.current_price"]     = ("Current", "Текущая"),
            ["inv.value"]             = ("Value", "Стоимость"),
            ["inv.pl"]                = ("P&L", "П/У"),
            ["inv.total"]             = ("📊 Total", "📊 Общий итог"),
            ["inv.total_units"]       = ("Total units", "Всего единиц"),
            ["inv.transport"]         = ("🚐 Transport", "🚐 Транспорт"),
            ["inv.warehouse"]         = ("🏭 Warehouse", "🏭 Склад"),
            ["inv.capacity"]          = ("Capacity", "Вместимость"),
            ["inv.create_character"]  = ("Create a character to view your inventory.", "Создайте персонажа для просмотра инвентаря."),
            ["inv.empty_title"]       = ("📭 Inventory is empty", "📭 Инвентарь пуст"),
            ["inv.empty_desc"]        = ("You don't have any items yet. Visit the Market or Exchange to buy something!", "У тебя пока нет товаров. Иди на Рынок или Биржу, чтобы что-нибудь купить!"),
            ["inv.no_transport"]      = ("No transport yet. Visit Logistics to buy one!", "Нет транспорта. Иди в Логистику, чтобы купить!"),
            ["inv.no_warehouse"]      = ("No warehouse. Buy land in Logistics first!", "Нет склада. Сначала купи землю в Логистике!"),
            ["inv.pcs"]               = ("pcs", "шт."),
            ["inv.raw_short"]         = ("Raw", "Сырьё"),
            ["inv.prod_short"]        = ("Products", "Продукция"),
            ["inv.actions"]           = ("Actions", "Действия"),
            ["inv.list_for_sale"]     = ("List for Sale", "Выставить на продажу"),
            ["inv.list_modal_title"]  = ("List {0} for Sale", "Выставить {0} на продажу"),
            ["inv.list_quantity"]     = ("Quantity to sell:", "Кол-во для продажи:"),
            ["inv.list_price"]        = ("Price per unit:", "Цена за единицу:"),
            ["inv.list_auto_repeat"]  = ("Auto-repeat listing after sale", "Авто-продление объявления"),
            ["inv.list_fee_warning"]  = ("Platform takes 10% commission on sale.", "Платформа берет 10% комиссии при продаже."),
            ["inv.list_cancel"]       = ("Cancel", "Отмена"),
            ["inv.list_confirm"]      = ("List Item", "Выставить"),
            ["inv.list_max"]          = ("Max", "Макс"),
            ["inv.list_success"]      = ("Successfully listed {0} x {1} for {2:C} each!", "Успешно выставлено {0} x {1} по {2:C} за шт!"),
            ["inv.list_error"]        = ("Error: {0}", "Ошибка: {0}"),
            ["inv.list_quantity_invalid"] = ("Invalid quantity selected.", "Выбрано неверное количество."),
            ["inv.list_price_invalid"] = ("Price must be greater than zero.", "Цена должна быть больше нуля."),


            // ----- Market -----
            ["market.title"]          = ("Market", "Рынок"),
            ["market.price"]          = ("Price", "Цена"),
            ["market.available"]      = ("Available", "Доступно"),
            ["market.history"]        = ("History", "История"),
            ["market.actions"]        = ("Actions", "Действия"),
            ["market.buy"]            = ("Buy", "Купить"),
            ["market.sell"]           = ("Sell", "Продать"),

            // ----- Stock Exchange -----
            ["exchange.title"]            = ("Stock Exchange", "Фондовая биржа"),
            ["exchange.create_player"]    = ("Please create a player first!", "Сначала создайте игрока!"),
            ["exchange.access_denied"]    = ("Access Denied!", "Доступ закрыт!"),
            ["exchange.need_car"]         = ("You need a car to travel to the Stock Exchange.", "Чтобы приехать на биржу, нужна машина."),
            ["exchange.visit_market"]     = ("Visit the Market to buy one.", "Купить её можно на Рынке."),
            ["exchange.closed"]           = ("Closed!", "Закрыто!"),
            ["exchange.hours"]            = ("The Stock Exchange is open from 09:00 to 17:00.", "Биржа работает с 09:00 до 17:00."),
            ["exchange.current_time"]     = ("Current time", "Текущее время"),
            ["exchange.sabotage_title"]   = ("🛑 SYSTEM LOCKED (SABOTAGE)", "🛑 СИСТЕМА ЗАБЛОКИРОВАНА (САБОТАЖ)"),
            ["exchange.sabotage_desc"]    = ("Trading is unavailable. Awaiting connection recovery…", "Торговля недоступна. Ожидайте восстановления связи…"),
            ["exchange.trip_cargo"]       = ("Trip", "Рейс"),
            ["exchange.warehouse_space"]  = ("Warehouse", "Склад"),
            ["exchange.sell_all"]         = ("Sell all", "Продать всё"),
            ["exchange.price_history"]    = ("📈 Price History", "📈 История цены"),
            ["exchange.min"]              = ("Min", "Мин"),
            ["exchange.max"]              = ("Max", "Макс"),
            ["exchange.current_short"]    = ("Current", "Текущая"),
            ["exchange.oldest"]           = ("← Oldest", "← Ранее"),
            ["exchange.latest"]           = ("Latest →", "Сейчас →"),
            ["exchange.points_tracked"]   = ("price points tracked", "точек цены записано"),
            ["exchange.nothing_to_sell"]  = ("You have no {0} to sell!", "У вас нет {0} для продажи!"),

            // ----- Logistics -----
            ["log.title"]             = ("🚛 Logistics", "🚛 Логистика"),
            ["log.capacity"]          = ("Capacity", "Вместимость"),
            ["log.finance"]           = ("Finance", "Финансы"),
            ["log.current_assets"]    = ("Current assets", "Текущие активы"),
            ["log.transport"]         = ("Transport", "Транспорт"),
            ["log.land"]              = ("Land", "Земля"),
            ["log.warehouses"]        = ("Warehouses", "Склады"),
            ["log.license"]           = ("License", "Лицензия"),
            ["log.none"]              = ("None", "Нет"),
            ["log.transport_desc"]    = ("A vehicle is mobile storage. Bigger truck = more cargo.", "Транспорт = мобильное хранилище. Чем больше машина, тем больше можешь возить."),
            ["log.land_desc"]         = ("Land is required to build warehouses. Bigger plot unlocks bigger warehouses.", "Земля нужна для постройки склада. Чем больше участок, тем больше склад можно построить."),
            ["log.land_plots"]        = ("Land plots", "Земельные участки"),
            ["log.max_warehouse"]     = ("Max warehouse: level", "Макс. склад: уровень"),
            ["log.trade_in"]          = ("Trade-in", "Обмен"),
            ["log.sell_at_60"]        = ("Sell (60%)", "Продать (60%)"),
            ["log.cannot_afford"]     = ("Can't afford", "Не хватает"),
            ["log.sell_first"]        = ("Sell current first", "Сначала продай текущий"),
            ["log.sell_warehouses_first"] = ("Sell warehouses first", "Сначала продай склады"),
            ["log.create_character"]  = ("Create a character to manage logistics.", "Создайте персонажа для управления логистикой."),
            ["log.money"]             = ("Money", "Деньги"),
            ["log.factories"]         = ("Factories", "Заводы"),
            ["log.warehouses_h"]      = ("Warehouses", "Склады"),
            ["log.level_short"]       = ("Lv.", "Ур."),
            ["log.no"]                = ("❌ None", "❌ Нет"),
            ["log.transport_h"]       = ("🚗 Transport", "🚗 Транспорт"),
            ["log.sell_60_pct"]       = ("Sell (60%)", "Продать (60%)"),
            ["log.buy"]               = ("Buy", "Купить"),
            ["log.not_enough"]        = ("Can't afford", "Не хватает"),
            ["log.trade_in_label"]    = ("Trade-in", "Trade-in"),
            ["log.land_title"]        = ("🏞 Land Plots", "🏞 Земельные участки"),
            ["log.my_land_plots"]      = ("🏞️ My Land Plots", "🏞️ Мои участки"),
            ["log.my_land_plots_desc"] = ("View and manage your owned land plots. Sell plots when no longer needed.", "Просмотр и управление вашими земельными участками. Продавайте участки, когда они больше не нужны."),
            ["log.land_limit"]         = ("Plot limit (upgrade license)", "Лимит участков (улучши лицензию)"),
            ["log.no_lands"]           = ("🏞️ You do not own any land plots. Buy one below!", "🏞️ У вас нет земельных участков. Купите участок ниже!"),
            ["land.smallplot"]         = ("Small Plot", "Маленький участок"),
            ["land.mediumplot"]        = ("Medium Plot", "Средний участок"),
            ["land.largeplot"]         = ("Large Plot", "Большой участок"),
            ["log.max_wh_level"]      = ("Max warehouse: level", "Макс. склад: уровень"),
            ["log.sell_70_pct"]       = ("Sell (70%)", "Продать (70%)"),
            ["log.sell_current_first"] = ("Sell the current one first", "Сначала продай текущий"),
            ["log.warehouses_title"]  = ("📦 Warehouses", "📦 Склады"),
            ["log.warehouses_desc"]   = ("A warehouse = permanent storage. Needs a land plot. Buy a trading license for more warehouses!", "Склад = постоянное хранилище. Требует земельного участка. Купи торговую лицензию для больше складов!"),
            ["log.capacity_wh"]       = ("Capacity", "Вместимость"),
            ["log.upkeep"]            = ("Upkeep", "Обслуживание"),
            ["log.per_month"]         = ("/mo", "/мес"),
            ["log.sell_50_pct"]       = ("Sell (50%)", "Продать (50%)"),
            ["log.capacity_plus"]     = ("Capacity: +", "Вместимость: +"),
            ["log.requires_plot"]     = ("Requires plot lv.", "Требует участок ур."),
            ["log.buy_land_first"]    = ("Buy land first", "Сначала купи землю"),
            ["log.plot_too_small"]    = ("Plot too small", "Участок слишком мал"),
            ["log.wh_limit"]          = ("Warehouse limit (buy a license)", "Лимит складов (купи лицензию)"),
            ["log.build"]             = ("Build", "Построить"),
            ["log.industrial_title"] = ("🏢 Industrial Facilities", "🏢 Промышленные объекты"),
            ["log.industrial_desc"]   = ("Factories boost production efficiency by 100% for matching goods.", "Заводы повышают эффективность производства на 100% для соответствующих товаров."),
            ["log.target"]            = ("Target", "Цель"),
            ["log.bonus"]             = ("Bonus: +100% to output", "Бонус: +100% к выходу продукции"),
            ["log.built"]             = ("Built", "Построено"),
            ["log.need_land"]         = ("Need land", "Нужна земля"),
            ["log.build_factory"]     = ("Build factory", "Построить завод"),
            ["log.license_title"]     = ("🎫 Trading License", "🎫 Торговая лицензия"),
            ["log.license_desc"]      = ("A license allows you to own more warehouses.", "Лицензия позволяет иметь больше складов."),
            ["log.current_level"]     = ("Current level", "Текущий уровень"),
            ["log.max_wh"]            = ("Max warehouses", "Макс. складов"),
            ["log.basic"]             = ("Basic", "Базовая"),
            ["log.advanced"]          = ("Advanced", "Продвинутая"),
            ["log.master"]            = ("Master", "Мастер-лицензия"),
            ["log.active"]            = ("✅ Active", "✅ Активна"),
            ["log.buy_level_first"]   = ("Buy lv. {0} first", "Сначала купи ур. {0}"),
            ["log.info_title"]        = ("ℹ️ How does it work?", "ℹ️ Как это работает?"),
            ["log.info_1"]            = ("Transport — mobile storage. Without a car you can't trade on the exchange.", "Транспорт — мобильное хранение. Без машины нельзя торговать на бирже."),
            ["log.info_2"]            = ("Land — required to build a warehouse.", "Земля — нужна для постройки склада."),
            ["log.info_3"]            = ("Warehouse — adds capacity but requires monthly upkeep.", "Склад — добавляет вместимость, но требует ежемесячной оплаты."),
            ["log.info_4"]            = ("License — allows multiple warehouses at once.", "Лицензия — позволяет иметь несколько складов одновременно."),
            ["log.info_5"]            = ("When upgrading transport — trade-in is 60% of the old vehicle's cost.", "При покупке большего транспорта — trade-in за 60% стоимости старого."),
            ["log.free_short"]        = ("Free", "Свободно"),
            ["log.factories_list"]    = ("Factories", "Заводы"),
            ["log.license_active_level"] = ("License", "Лицензия"),
            ["log.my_fleet"]              = ("🚢 My Fleet", "🚢 Мой автопарк"),
            ["log.my_fleet_desc"]         = ("Manage your fleet of vehicles. Cargo capacities are cumulative.", "Управляйте своим автопарком. Грузовместимости суммируются."),
            ["log.no_vehicles"]           = ("You don't have any vehicles. Buy one below!", "У вас нет транспорта. Купите что-нибудь ниже!"),
            ["log.available_vehicles"]    = ("🛒 Available Vehicles", "🛒 Доступный транспорт"),
            ["log.buy_more_vehicles_desc"] = ("Purchase additional vehicles to increase your total cargo capacity.", "Покупайте дополнительный транспорт, чтобы увеличить общую вместимость."),
            ["log.owned_count"]           = ("Owned", "В наличии"),
            ["log.bought_for"]            = ("Bought for", "Куплено за"),

            // ----- Bank -----
            ["bank.title"]              = ("🏦 Bank", "🏦 Банк"),
            ["bank.deposit"]            = ("Deposit", "Депозит"),
            ["bank.withdraw"]           = ("Withdraw", "Снять"),
            ["bank.take_loan"]          = ("Take loan", "Взять кредит"),
            ["bank.current_rate"]       = ("Current rate", "Текущая ставка"),
            ["bank.create_character"]   = ("Create a character to access the bank.", "Создайте персонажа для доступа к банку."),
            ["bank.no_access"]          = ("No access!", "Нет доступа!"),
            ["bank.need_car"]           = ("You need a vehicle to travel to the bank.", "Нужен транспорт для поездки в банк."),
            ["bank.buy_car_logistics"] = ("Buy one in Logistics.", "Купите его в Логистике."),
            ["bank.closed"]             = ("Closed!", "Закрыто!"),
            ["bank.hours"]              = ("The bank is open from 09:00 to 17:00.", "Банк работает с 09:00 до 17:00."),
            ["bank.current_time"]       = ("Current time", "Текущее время"),
            ["bank.cash"]               = ("💵 Cash", "💵 Наличные"),
            ["bank.on_deposit"]         = ("💰 On deposit", "💰 На депозите"),
            ["bank.annual"]             = ("% annual", "% годовых"),
            ["bank.debt"]               = ("📋 Debt", "📋 Долги"),
            ["bank.deposit_card"]       = ("💰 Deposit", "💰 Депозит"),
            ["bank.loan_card"]          = ("💳 Loan", "💳 Кредит"),
            ["bank.insurance_card"]     = ("🛡 Insurance", "🛡 Страхование"),
            ["bank.amount"]             = ("Amount", "Сумма"),
            ["bank.term_months"]        = ("Term (months)", "Срок (мес.)"),
            ["bank.make_deposit"]       = ("📥 Deposit", "📥 Внести"),
            ["bank.make_withdraw"]      = ("📤 Withdraw", "📤 Снять"),
            ["bank.insurance_desc"]     = ("Protection against natural disasters. Covers 80% of losses from lost goods.", "Защита от природных катастроф. Покрывает 80% убытков при потере товара."),
            ["bank.insured"]            = ("✅ INSURED", "✅ ЗАСТРАХОВАН"),
            ["bank.until"]              = ("Until", "До"),
            ["bank.no_protection"]      = ("⚠️ NO PROTECTION", "⚠️ НЕТ ЗАЩИТЫ"),
            ["bank.capital_risk"]       = ("Capital at risk!", "Риск потери капитала!"),
            ["bank.buy_policy"]         = ("Buy policy ($25,000)", "Купить полис ($25,000)"),
            ["bank.active_30_days"]     = ("🛡 Active for 30 days", "🛡 Активно на 30 дней"),
            ["bank.active_loans"]       = ("📋 Active Loans", "📋 Активные кредиты"),
            ["bank.col_amount"]         = ("Amount", "Сумма"),
            ["bank.col_term"]           = ("Term", "Срок"),
            ["bank.col_penalty"]        = ("Penalty", "Штраф"),
            ["bank.col_status"]         = ("Status", "Статус"),
            ["bank.col_action"]         = ("Action", "Действие"),
            ["bank.days_short"]         = ("d", "дн."),
            ["bank.overdue"]            = ("Overdue", "Просрочен"),
            ["bank.soon"]               = ("Soon!", "Скоро!"),
            ["bank.active"]             = ("Active", "Активен"),
            ["bank.repay"]              = ("Repay", "Погасить"),
            ["bank.financial_report"]   = ("📊 Financial Report", "📊 Финансовый отчёт"),
            ["bank.monthly_income"]     = ("Income (month)", "Доходы (месяц)"),
            ["bank.monthly_expenses"]   = ("Expenses (month)", "Расходы (месяц)"),
            ["bank.balance"]            = ("Balance", "Баланс"),
            ["bank.net_worth"]          = ("Net worth", "Чистая стоимость"),
            ["bank.report_history"]     = ("Report history", "История отчётов"),
            ["bank.col_day"]            = ("Day", "День"),
            ["bank.col_start"]          = ("Start", "Начало"),
            ["bank.col_end"]            = ("End", "Конец"),
            ["bank.col_change"]         = ("Change", "Изменение"),
            ["bank.day_n"]              = ("Day", "День"),
            ["bank.loan_min"]           = ("Minimum loan amount: $100", "Минимальная сумма кредита: $100"),
            ["bank.loan_term_min"]      = ("Loan term minimum 1 month", "Срок кредита минимум 1 месяц"),
            ["bank.loan_approved"]      = ("✅ Loan {0} for {1} months at {2}", "✅ Кредит {0} на {1} мес. под {2}"),
            ["bank.months_short"]       = ("mo.", "мес."),
            ["bank.insufficient_funds"] = ("❌ Insufficient funds! Need {0}, have {1}", "❌ Недостаточно денег! Нужно {0}, есть {1}"),
            ["bank.loan_repaid"]        = ("✅ Loan {0} repaid + penalty {1}", "✅ Погашен кредит {0} + штраф {1}"),
            ["bank.base_rate"]          = ("Base annual rate: {0}", "Базовая годовая ставка: {0}"),
            ["bank.reputation_discount"] = ("Reputation discount: -{0}", "Скидка за репутацию: -{0}"),
            ["bank.your_rate"]          = ("Your loan rate: {0}", "Ваша ставка по кредиту: {0}"),

            // ----- Profile -----
            ["profile.title"]           = ("👤 Player Profile", "👤 Профиль игрока"),
            ["profile.reputation"]      = ("Reputation", "Репутация"),
            ["profile.license"]         = ("Trading License", "Торговая лицензия"),
            ["profile.trade_volume"]    = ("Trading Volume", "Торговый оборот"),
            ["profile.license_level_0"] = ("Rookie (No License)", "Новичок (Без лицензии)"),
            ["profile.license_level_1"] = ("Licensed Trader", "Лицензированный торговец"),
            ["profile.license_level_2"] = ("Professional Trader", "Профессиональный торговец"),
            ["profile.license_level_3"] = ("Tycoon", "Магнат"),
            ["profile.statistics"]      = ("Trading Performance", "Статистика и аналитика"),
            ["profile.total_trades"]    = ("Total Trades", "Всего сделок"),
            ["profile.profitable_trades"] = ("Profitable Trades", "Прибыльные сделки"),
            ["profile.success_rate"]    = ("Success Rate", "Доля прибыльных сделок"),
            ["profile.assets_summary"]  = ("Capital Assets Valuation", "Оценка капитала и активов"),
            ["profile.development_history"] = ("Development History (Monthly Reports)", "История развития (Ежемесячные отчеты)"),
            ["profile.no_reports"]      = ("No monthly financial reports filed yet. Keep playing to record your history!", "Ежемесячные отчеты пока не сформированы. Продолжайте играть, чтобы создать историю!"),
            ["profile.col_month"]       = ("Month", "Месяц"),
            ["profile.col_day"]         = ("Day", "День"),
            ["profile.col_income"]      = ("Income", "Доходы"),
            ["profile.col_expenses"]    = ("Expenses", "Расходы"),
            ["profile.col_net_change"]  = ("Net Profit", "Чистая прибыль"),
            ["profile.col_ending_balance"] = ("Ending Capital", "Конечный капитал"),
            ["profile.scenario"]        = ("Active Challenge", "Активный сценарий"),
            ["profile.freeplay"]        = ("Free Play Mode", "Свободный режим"),

            // ----- Production -----
            ["prod.title"]            = ("🏭 Production", "🏭 Производство"),
            ["prod.auto"]             = ("Auto", "Авто"),
            ["prod.produce"]          = ("Produce", "Производить"),
            ["prod.no_resources"]     = ("❌ Not enough resources", "❌ Нет ресурсов"),
            ["prod.no_money"]         = ("💸 Not enough money", "💸 Нет денег"),
            ["prod.no_space"]         = ("📦 No space", "📦 Нет места"),
            ["prod.create_character"] = ("Create a character to access production.", "Создайте персонажа для доступа к производству."),
            ["prod.need_warehouse"]   = ("⚠ Warehouse required", "⚠ Требуется склад"),
            ["prod.need_warehouse_desc"] = ("Production needs a warehouse. Buy land and build one in Logistics.", "Для производства нужен склад. Купите землю и постройте склад в разделе Логистика."),
            ["prod.balance"]          = ("💰 Balance", "💰 Баланс"),
            ["prod.warehouse"]        = ("📦 Warehouse", "📦 Склад"),
            ["prod.requires"]         = ("📥 Requires", "📥 Требуется"),
            ["prod.in_stock"]         = ("in stock", "в наличии"),
            ["prod.produces"]         = ("📤 Produces", "📤 Производит"),
            ["prod.factory_bonus"]    = ("(+100% from factory)", "(+100% за завод)"),
            ["prod.qty_label"]        = ("Qty:", "Кол-во:"),
            ["prod.produce_btn"]      = ("⚙️ Produce", "⚙️ Произвести"),
            ["prod.auto_label"]       = ("Auto", "Авто"),
            ["prod.inventory_title"]  = ("📦 Inventory (for production)", "📦 Инвентарь (для производства)"),
            ["prod.pcs"]              = ("pcs", "шт."),
            ["prod.empty_inventory"]  = ("Inventory is empty. Buy resources on the exchange!", "Инвентарь пуст. Купите ресурсы на бирже!"),
            ["prod.produced"]         = ("✅ Produced: {0}! Cost: {1}", "✅ Произведено: {0}! Затраты: {1}"),
            ["prod.auto_settings"]            = ("⚙️ Automation Controls", "⚙️ Настройка авто-лимитов"),
            ["prod.min_reserve"]              = ("Min Input Reserve (MIN)", "Минимальный резерв сырья (MIN)"),
            ["prod.min_reserve_desc"]         = ("Factory pauses if raw material falls below this amount.", "Производство остановится, если сырья останется меньше этого числа."),
            ["prod.max_stock"]                = ("Max Output Stock (MAX)", "Предельный запас готового товара (MAX)"),
            ["prod.max_stock_desc"]           = ("Factory pauses once output stock reaches this cap.", "Производство остановится при накоплении указанного объема готового товара."),

            // ----- Bar / Casino -----
            ["bar.title"]             = ("🍺 Trader's Bar", "🍺 Бар «У Трейдера»"),
            ["bar.create_character"]  = ("Create a character to visit the bar.", "Создайте персонажа для посещения бара."),
            ["bar.your_status"]       = ("Your status", "Твоё состояние"),
            ["bar.money"]             = ("Money", "Деньги"),
            ["bar.state"]             = ("State", "Состояние"),
            ["bar.sober_up_at"]       = ("Sober up by", "Протрезвеешь к"),
            ["bar.tipsy_warning"]     = ("⚠️ Careful! Tipsy players have lower odds!", "⚠️ Осторожно! В пьяном виде шансы на выигрыш ниже!"),
            ["bar.menu"]              = ("🍻 Drinks menu", "🍻 Меню напитков"),
            ["bar.beer"]              = ("Beer", "Пиво"),
            ["bar.whiskey"]           = ("Whiskey", "Виски"),
            ["bar.cocktail"]          = ("Cocktail", "Коктейль"),
            ["bar.order"]             = ("Order", "Заказать"),
            ["bar.socialize"]         = ("👥 Socialize", "👥 Общение"),
            ["bar.mingle_hint"]       = ("Chat with patrons — you might stumble on a good deal!", "Поговори с посетителями — может найдёшь выгодную сделку!"),
            ["bar.approach"]          = ("Approach someone", "Подойти к кому-нибудь"),
            ["bar.get_drink_first"]   = ("Order a drink first to loosen up!", "Закажи выпить, чтобы раскрепоститься!"),
            ["bar.offer"]             = ("💰 Offer!", "💰 Предложение!"),
            ["bar.total"]             = ("Total", "Итого"),
            ["bar.accept"]            = ("✅ Accept", "✅ Принять"),
            ["bar.decline"]           = ("❌ Decline", "❌ Отказаться"),
            ["bar.casino"]            = ("🎰 Casino \"Luck\"", "🎰 Казино «Удача»"),
            ["bar.slots"]             = ("🎰 Slots", "🎰 Слоты"),
            ["bar.dice"]              = ("🎲 Dice", "🎲 Кости"),
            ["bar.blackjack"]         = ("🃏 Blackjack", "🃏 Блэкджек"),
            ["bar.roulette"]          = ("🎡 Roulette", "🎡 Рулетка"),
            ["bar.playing"]           = ("🎲 Playing…", "🎲 Играем…"),
            ["bar.dealer"]            = ("Dealer", "Дилер"),
            ["bar.your_cards"]        = ("Your cards", "Твои карты"),
            ["bar.sum"]               = ("Sum", "Сумма"),
            ["bar.spin_reels"]        = ("Spin the reels!", "Крути барабаны!"),
            ["bar.roll_dice"]         = ("Roll the dice!", "Брось кубики!"),
            ["bar.beat_dealer"]       = ("Try to beat the dealer!", "Попробуй обыграть дилера!"),
            ["bar.place_bets"]        = ("Place your bets!", "Делайте ваши ставки!"),
            ["bar.bet"]               = ("💰 Bet", "💰 Ставка"),
            ["bar.spin"]              = ("SPIN!", "КРУТИТЬ!"),
            ["bar.throw_dice"]        = ("ROLL THE DICE", "БРОСИТЬ КОСТИ"),
            ["bar.combo_pair"]        = ("Pair", "Пара"),
            ["bar.combo_two_pair"]    = ("Two pairs", "Две пары"),
            ["bar.combo_three"]       = ("Three of a kind", "Тройка"),
            ["bar.combo_straight"]    = ("Straight", "Стрит"),
            ["bar.combo_full_house"]  = ("Full house", "Фулл-хаус"),
            ["bar.combo_four"]        = ("Four of a kind", "Каре"),
            ["bar.combo_poker"]       = ("Poker (5)", "Покер (5)"),
            ["bar.rolls_left"]        = ("Rolls left", "Бросков осталось"),
            ["bar.click_to_hold"]     = ("Click a die to hold it", "Нажми на кубик чтобы сохранить его"),
            ["bar.roll"]              = ("ROLL", "БРОСИТЬ"),
            ["bar.left"]              = ("left", "осталось"),
            ["bar.pick_combo"]        = ("Pick a combination to score:", "Выбери комбинацию для подсчёта:"),
            ["bar.take_winnings"]     = ("💰 TAKE WINNINGS", "💰 ЗАБРАТЬ ВЫИГРЫШ"),
            ["bar.deal_cards"]        = ("DEAL CARDS", "РАЗДАТЬ КАРТЫ"),
            ["bar.hit"]               = ("👆 HIT", "👆 ЕЩЁ"),
            ["bar.stand"]             = ("✋ STAND", "✋ ХВАТИТ"),
            ["bar.red"]               = ("🔴 RED (x2)", "🔴 КРАСНОЕ (x2)"),
            ["bar.black"]             = ("⚫ BLACK (x2)", "⚫ ЧЁРНОЕ (x2)"),
            ["bar.number"]            = ("🎯 NUMBER (x35)", "🎯 НОМЕР (x35)"),
            ["bar.drunk_lowers"]      = ("🍺 Drunk state lowers odds! Level", "🍺 Опьянение снижает шансы! Уровень"),
            ["bar.games_played"]      = ("Games", "Игр"),
            ["bar.wins"]               = ("Wins", "Выигрыши"),
            ["bar.losses"]            = ("Losses", "Проигрыши"),
            ["bar.rumors_heard"]      = ("👂 Rumors heard", "👂 Услышанные слухи"),
            ["bar.shadow_ops"]        = ("🕵️‍♂️ Shadow Operations", "🕵️‍♂️ Теневые операции"),
            ["bar.shadow_desc"]       = ("Hire people here to deal with \"special\" problems with competitors.", "Здесь можно нанять людей для решения «особых» проблем с конкурентами."),
            ["bar.rival"]             = ("Rival", "Конкурент"),
            ["bar.actions"]           = ("Actions", "Действия"),
            ["bar.sabotaged_badge"]   = ("Sabotaged", "Саботаж"),
            ["bar.your_division"]     = ("Your division", "Твоё подразделение"),
            ["bar.intel"]             = ("👁 Intel ($5k)", "👁 Разведка ($5k)"),
            ["bar.sabotage"]          = ("🧨 Sabotage", "🧨 Саботаж"),
            ["bar.takeover"]          = ("🏢 Takeover", "🏢 Поглощение"),
            ["bar.no_enemies"]        = ("No serious enemies on the market yet…", "Пока у тебя нет серьезных врагов на рынке..."),
            ["bar.deal_declined"]     = ("You declined the deal.", "Ты отказался от сделки."),
            ["bar.insufficient_bet"]  = ("💸 Not enough money to bet!", "💸 Недостаточно денег для ставки!"),
            ["bar.bust"]              = ("💥 Bust! You lose.", "💥 Перебор! Ты проиграл."),
            ["bar.dealer_bust"]       = ("🎉 Dealer busted! You won {0}!", "🎉 Дилер перебрал! Ты выиграл {0}!"),
            ["bar.you_won"]           = ("🎉 {0} > {1}! You won {2}!", "🎉 {0} > {1}! Ты выиграл {2}!"),
            ["bar.you_lost"]          = ("😢 {0} < {1}. You lost {2}.", "😢 {0} < {1}. Ты проиграл {2}."),
            ["bar.push"]              = ("🤝 Push! {0} = {1}. Bet returned.", "🤝 Ничья! {0} = {1}. Ставка возвращена."),
            ["bar.dice_score_win"]    = ("🎲 {0}! Winnings: {1}!", "🎲 {0}! Выигрыш: {1}!"),
            ["bar.dice_score_lose"]   = ("😢 {0} not found. Bet lost.", "😢 {0} не найдено. Ставка потеряна."),
            ["bar.combo_sum"]         = ("Sum", "Сумма"),
            ["bar.combo_two_pair_short"] = ("2 Pairs", "2 Пары"),
            ["bar.combo_poker_excl"]  = ("POKER!", "ПОКЕР!"),
            ["bar.poker"]                     = ("🃏 Poker", "🃏 Покер"),
            ["bar.poker_subtitle"]            = ("Video Poker: Jacks or Better", "Видео-покер: Jacks or Better"),
            ["bar.poker_hold"]                = ("🔒 HELD", "🔒 ДЕРЖАТЬ"),
            ["bar.poker_hold_hint"]           = ("Click cards to HOLD, then click DRAW to replace others", "Нажми на карты, чтобы ДЕРЖАТЬ их, затем нажми ОБМЕН, чтобы заменить остальные"),
            ["bar.poker_draw"]                = ("🔄 DRAW / REPLACE", "🔄 ОБМЕНЯТЬ КАРТЫ"),
            ["bar.poker_deal"]                = ("DEAL CARDS", "РАЗДАТЬ КАРТЫ"),
            ["bar.poker_drunk_slip"]          = ("🥴 You are too drunk and accidentally dropped held card №{0}!", "🥴 Ты слишком пьян и случайно выронил удержанную карту №{0}!"),
            ["bar.poker_win"]                 = ("🎉 {0}! Winnings: {1}!", "🎉 {0}! Выигрыш: {1}!"),
            ["bar.poker_lose"]                = ("😢 No combination. Bet lost.", "😢 Нет комбинации. Ставка проиграна."),
            ["bar.payout_royal"]              = ("Royal Flush (x250)", "Роял-флеш (x250)"),
            ["bar.payout_straight_flush"]     = ("Straight Flush (x50)", "Стрит-флеш (x50)"),
            ["bar.payout_four"]               = ("Four of a Kind (x25)", "Каре (x25)"),
            ["bar.payout_full_house"]         = ("Full House (x9)", "Фулл-хаус (x9)"),
            ["bar.payout_flush"]              = ("Flush (x6)", "Флеш (x6)"),
            ["bar.payout_straight"]           = ("Straight (x4)", "Стрит (x4)"),
            ["bar.payout_three"]              = ("Three of a Kind (x3)", "Тройка (x3)"),
            ["bar.payout_two_pair"]           = ("Two Pairs (x2)", "Две пары (x2)"),
            ["bar.payout_jacks"]              = ("Jacks or Better (x1)", "Валеты и выше (x1)"),
            ["bar.tier_bronze"]               = ("🥉 Standard", "🥉 Новичок"),
            ["bar.tier_silver"]               = ("🥈 High Roller", "🥈 Богач"),
            ["bar.tier_gold"]                 = ("🥇 VIP", "🥇 VIP"),
            ["bar.tier_locked"]               = ("🔒 Locked (Need {0})", "🔒 Закрыто (Нужно {0})"),
            // Bar encounters (random flavor text when approaching someone)
            ["bar.enc_drink_together"] = ("A stranger sits down at your table and offers to drink together.",
                                          "Подсел какой-то мужик, предлагает выпить вместе."),
            ["bar.enc_barman_stories"] = ("The barman starts telling market stories.",
                                          "Бармен рассказывает истории о рынке."),
            ["bar.enc_fellow_trader"]  = ("You spot a fellow trader in the corner.",
                                          "Заметил знакомого торговца в углу."),
            ["bar.enc_loud_crowd"]     = ("A loud group nearby is discussing deals.",
                                          "Рядом шумная компания обсуждает сделки."),
            // Buy-him-a-drink interaction
            ["bar.buy_him_drink"]      = ("🍻 Buy him a drink ({0})", "🍻 Угостить его ({0})"),
            ["bar.buy_him_drink_hint"] = ("Buy a round — 50/50 chance he'll share a rumor or a deal… or just pocket the drink and leave.",
                                          "Угости его — 50/50 что он поделится слухом или сделкой… или просто заберёт выпивку и свалит."),
            ["bar.sober_no_meet"]      = ("You're sober. Order something to start a conversation!",
                                          "Ты трезвый. Закажи что-нибудь, чтобы завести разговор!"),
            ["bar.deal_offer_text"]    = ("He offers {0} × {1} at {2} each!",
                                          "Он предлагает {0} × {1} по {2} за штуку!"),
            ["bar.stranger_deal"]      = ("You bought him a drink. He relaxes and offers {0} × {1} at {2} each!",
                                          "Ты угостил его. Он расслабился и предлагает {0} × {1} по {2} за штуку!"),
            ["bar.stolen_deal"]        = ("You bought him a drink. He looked around shiftily and whispered: «Listen, I've got some hot stolen {0}! I'll sell you {1} units for a huge discount — only {2} each!»",
                                          "Ты угостил его выпивкой. Он воровато огляделся и прошептал: «Слушай, есть горячие краденые {0}! Отдам {1} шт. с огромной скидкой — всего по {2} за штуку!»"),
            ["bar.police_raid_bounty"] = ("🚓 POLICE RAID! The police broke in and confiscated the stolen {0}! However, as a reward for cooperation, you received a 10% bounty of {1}!",
                                          "🚓 ОБЛАВА ПОЛИЦИИ! Полицейские ворвались и конфисковали краденые {0}! Тем не менее, за сотрудничество вам выплатили 10% награды в размере {1}!"),
            ["bar.police_raid_no_bounty"] = ("🚓 POLICE RAID! The police broke in and confiscated the stolen {0}! You got lucky and weren't arrested, but they gave you no reward. Total loss!",
                                            "🚓 ОБЛАВА ПОЛИЦИИ! Полицейские ворвались и конфисковали краденые {0}! Вам повезло избежать ареста, но награду вам не дали. Полный убыток!"),
            ["bar.stranger_rumor"]     = ("You bought him a drink. He leans in and whispers: «{0}»",
                                          "Ты угостил его. Он наклонился и шепчет: «{0}»"),
            // Scam outcomes when buying a drink for the stranger backfires (50% chance)
            ["bar.scam_drink_and_leave"] = ("He downs the drink in one gulp, mutters \"thanks\" and walks out the door. You've been had.",
                                            "Он залпом выпивает и, буркнув «спасибо», выходит. Тебя развели."),
            ["bar.scam_boring_story"]  = ("He rambles for an hour about his ex-wife and then leaves without a word. Well, that was a waste.",
                                          "Он час рассказывает про свою бывшую и молча уходит. Ну и зря потратился."),
            ["bar.scam_bathroom_exit"] = ("\"Be right back, toilet!\" he says — and you never see him again.",
                                          "«Я в туалет, сейчас вернусь!» — говорит он и пропадает навсегда."),

            // ----- Stock market -----
            ["stock.title"]           = ("📊 Stock Market", "📊 Фондовый рынок"),
            ["stock.create_character"] = ("Create a character to access the stock market.", "Создайте персонажа для доступа к фондовому рынку."),
            ["stock.no_access"]       = ("No access!", "Нет доступа!"),
            ["stock.need_car"]        = ("A car is required to visit the exchange.", "Нужна машина для поездки на биржу."),
            ["stock.buy_car_market"]  = ("Buy a vehicle in the Market section.", "Купите транспорт в разделе Рынок."),
            ["stock.closed"]          = ("Closed!", "Закрыто!"),
            ["stock.hours"]           = ("The stock market is open from {0}:00 to {1}:00.", "Фондовый рынок работает с {0}:00 до {1}:00."),
            ["stock.current_time"]    = ("Current time", "Текущее время"),
            ["stock.balance"]         = ("💰 Cash", "💰 Баланс"),
            ["stock.portfolio"]       = ("📊 Portfolio", "📊 Портфель"),
            ["stock.dividends"]       = ("💵 Dividends", "💵 Дивиденды"),
            ["stock.stocks"]          = ("📊 Stocks", "📊 Акции"),
            ["stock.fee"]             = ("Fee", "Комиссия"),
            ["stock.ticker"]          = ("Ticker", "Тикер"),
            ["stock.company"]         = ("Company", "Компания"),
            ["stock.price"]           = ("Price", "Цена"),
            ["stock.change"]          = ("Change", "Изменение"),
            ["stock.yield"]           = ("Yield", "Доходность"),
            ["stock.available"]       = ("Available", "Доступно"),
            ["stock.held"]            = ("Held", "В портфеле"),
            ["stock.actions"]         = ("Actions", "Действия"),
            ["stock.shares_short"]    = ("shares", "шт."),
            ["stock.buy"]             = ("Buy", "Купить"),
            ["stock.sell"]            = ("Sell", "Продать"),
            ["stock.sell_all"]        = ("Sell all", "Продать всё"),
            ["stock.chart"]           = ("📈 Chart", "📈 График"),
            ["stock.my_portfolio"]    = ("💼 My portfolio", "💼 Мой портфель"),
            ["stock.shares"]          = ("Shares", "Акций"),
            ["stock.avg_buy"]         = ("Avg. buy price", "Ср. цена покупки"),
            ["stock.current_price"]   = ("Current price", "Текущая цена"),
            ["stock.value"]           = ("Value", "Стоимость"),
            ["stock.pending_orders"]  = ("⏳ Pending orders", "⏳ Отложенные ордера"),
            ["stock.type"]            = ("Type", "Тип"),
            ["stock.action"]          = ("Action", "Действие"),
            ["stock.qty_short"]       = ("Qty", "Кол-во"),
            ["stock.order_limit"]     = ("Limit", "Лимит"),
            ["stock.order_stoploss"]  = ("Stop-loss", "Стоп-лосс"),
            ["stock.order_market"]    = ("Market", "Рыночный"),
            ["stock.buy_green"]       = ("🟢 Buy", "🟢 Купить"),
            ["stock.sell_red"]        = ("🔴 Sell", "🔴 Продать"),
            ["stock.cancel"]          = ("Cancel", "Отмена"),
            ["stock.create_order"]    = ("📝 Create order", "📝 Создать ордер"),
            ["stock.order_limit_opt"] = ("Limit", "Лимитный"),
            ["stock.place"]           = ("Place", "Разместить"),
            ["stock.oldest"]          = ("← Oldest", "← Старое"),
            ["stock.latest"]          = ("Latest →", "Новое →"),
            ["stock.chart_min"]       = ("Min", "Мин"),
            ["stock.chart_current"]   = ("Current", "Текущее"),
            ["stock.chart_max"]       = ("Max", "Макс"),
            ["stock.no_shares_to_sell"] = ("No shares to sell!", "Нет акций для продажи!"),

            // ----- Housing -----
            ["house.title"]           = ("🏠 Real estate", "🏠 Недвижимость"),
            ["house.create_character"] = ("Create a character to buy property.", "Создайте персонажа для покупки недвижимости."),
            ["house.your_home"]       = ("Your home", "Твоё жильё"),
            ["house.homeless"]        = ("Homeless", "Бездомный"),
            ["house.sleep_in_car"]    = ("You sleep in your car. This is bad for your health!", "Ты спишь в машине. Это опасно для здоровья!"),
            ["house.homeless_warning"] = ("⚠️ Every night in the car: reputation −1, and thieves may break in and steal up to 4% of your cash. Even a small room solves this.", "⚠️ Каждая ночь в машине: репутация −1, и воры могут вскрыть машину и утащить до 4% наличных. Даже маленькая комната решает проблему."),
            ["bar.closed_banner"]     = ("The bar is closed. Come back in the evening!", "Бар закрыт. Приходи вечером!"),
            ["bar.time_dilation_hint"] = ("Time flows slower while you're at the bar — enjoy the evening.", "Пока ты в баре, время течёт медленнее — наслаждайся вечером."),
            ["bar.dice_pick_target"]  = ("Declare your target BEFORE rolling — hit it in 3 rolls and get paid!", "Объяви цель ДО броска — соберёшь её за 3 броска, получишь выплату!"),
            ["bar.dice_target"]       = ("Target", "Цель"),
            ["house.rent"]            = ("Rent", "Аренда"),
            ["house.per_month"]       = ("month", "месяц"),
            ["house.per_month_short"] = ("/mo", "/мес"),
            ["house.capacity"]        = ("Capacity", "Вместимость"),
            ["house.guests"]          = ("guests", "гостей"),
            ["house.guests_short"]    = ("people", "чел."),
            ["house.birthday_bonus"]  = ("Birthday bonus", "Бонус на ДР"),
            ["house.birthday_gifts"]  = ("Birthday gifts", "Подарки на ДР"),
            ["house.sell_70"]         = ("Sell (for 70%)", "Продать (за 70%)"),
            ["house.finances"]        = ("💰 Finances", "💰 Финансы"),
            ["house.money"]           = ("Money", "Деньги"),
            ["house.reputation"]      = ("Reputation", "Репутация"),
            ["house.until_rent"]      = ("Next rent due in", "До оплаты аренды"),
            ["house.days"]            = ("days", "дней"),
            ["house.available"]       = ("🏘️ Available property", "🏘️ Доступная недвижимость"),
            ["house.owned_badge"]     = ("✓ Your home", "✓ Твоё жильё"),
            ["house.sell_current_first"] = ("Sell current first", "Сначала продай текущее"),
            ["house.not_enough"]      = ("Short by {0}", "Не хватает {0}"),
            ["house.buy"]             = ("Buy", "Купить"),
            ["house.birthday_info_title"] = ("🎂 How does housing affect Birthdays?", "🎂 Как жильё влияет на День Рождения?"),
            ["house.birthday_info_body"] = ("The bigger your home, the more friends will come on your birthday and the more gifts you'll get! Homeless players only get minimal gifts from passersby.", "Чем больше твоё жильё, тем больше друзей придёт на ДР и тем больше подарков ты получишь! Бездомные получают минимальные подарки от случайных прохожих."),
            ["house.your_homes"]         = ("🏡 Your Properties", "🏡 Ваша недвижимость"),
            ["house.total_homes"]        = ("Total owned", "Всего во владении"),
            ["house.name"]               = ("Name", "Название"),
            ["house.action"]             = ("Action", "Действие"),

            // ----- Save / Load -----
            ["save.title"]            = ("💾 Save / Load", "💾 Сохранение / Загрузка"),
            ["save.create_character"] = ("Create a character to save the game.", "Создайте персонажа для сохранения игры."),
            ["save.save_game"]        = ("💾 Save game", "💾 Сохранить игру"),
            ["save.name_label"]       = ("Save name", "Название сохранения"),
            ["save.name_placeholder"] = ("My save...", "Моё сохранение..."),
            ["save.save_btn"]         = ("💾 Save", "💾 Сохранить"),
            ["save.progress"]         = ("Current progress:", "Текущий прогресс:"),
            ["save.player"]           = ("Player", "Игрок"),
            ["save.money"]            = ("Money", "Деньги"),
            ["save.day"]              = ("Day", "День"),
            ["save.time"]              = ("Time", "Время"),
            ["save.load_game"]        = ("📂 Load game", "📂 Загрузить игру"),
            ["save.refresh"]          = ("🔄 Refresh", "🔄 Обновить"),
            ["save.empty"]            = ("No saved games. Create your first save!", "Нет сохранённых игр. Создай своё первое сохранение!"),
            ["save.col_name"]         = ("Name", "Название"),
            ["save.col_player"]       = ("Player", "Игрок"),
            ["save.col_day"]          = ("Day", "День"),
            ["save.col_money"]        = ("Money", "Деньги"),
            ["save.col_saved_at"]     = ("Saved", "Сохранено"),
            ["save.col_actions"]      = ("Actions", "Действия"),
            ["save.day_n"]            = ("Day {0}", "День {0}"),
            ["save.load_btn"]         = ("📂 Load", "📂 Загрузить"),
            ["save.info_title"]       = ("ℹ️ Info", "ℹ️ Информация"),
            ["save.info_location"]   = ("Saves are stored in: ", "Сохранения хранятся в: "),
            ["save.info_replace"]     = ("Loading will replace current progress", "Загрузка заменит текущий прогресс"),
            ["save.info_regular"]     = ("It's recommended to save regularly!", "Рекомендуется сохраняться регулярно!"),
            ["save.default_name"]     = ("Save {0}", "Сохранение {0}"),
            ["save.name_required"]    = ("❌ Enter a save name!", "❌ Введи название сохранения!"),

            // ----- Events -----
            ["events.title"]          = ("🎲 Events", "🎲 События"),
            ["events.create_character"] = ("Create a character to see events.", "Создайте персонажа для просмотра событий."),
            ["events.profile"]        = ("Your profile", "Ваш профиль"),
            ["events.name"]           = ("Name", "Имя"),
            ["events.money"]          = ("Money", "Деньги"),
            ["events.reputation"]     = ("Reputation", "Репутация"),
            ["events.none"]           = ("📭 No active events", "📭 Нет активных событий"),
            ["events.none_desc"]      = ("Keep playing — something will happen soon!", "Продолжайте играть — скоро что-нибудь произойдёт!"),
            ["events.insufficient"]   = ("(not enough money)", "(недостаточно денег)"),
            ["events.result"]         = ("Result:", "Результат:"),
            ["events.history"]        = ("📜 Event history", "📜 История событий"),
            ["events.completed"]      = ("Completed", "Завершено"),
            ["events.history_empty"]  = ("History is empty. Make decisions!", "История пуста. Принимай решения!"),
            ["events.expired"]        = ("Expired!", "Истекло!"),
            ["events.hours_short"]    = ("h", "ч"),
            ["events.minutes_short"]  = ("m", "м"),

            // ----- Scenarios / Challenges -----
            ["scenario.title"]                = ("🎯 Scenarios", "🎯 Сценарии"),
            ["scenario.subtitle"]             = ("Pick a challenge, race the clock.", "Выбери испытание и гонись за временем."),
            ["scenario.available"]            = ("Available scenarios", "Доступные сценарии"),
            ["scenario.active_header"]        = ("Active scenario", "Активный сценарий"),
            ["scenario.no_active"]            = ("No active scenario — you're in freeplay.", "Нет активного сценария — свободная игра."),
            ["scenario.start_btn"]            = ("▶ Start", "▶ Начать"),
            ["scenario.abandon_btn"]          = ("✖ Abandon", "✖ Отказаться"),
            ["scenario.status"]               = ("Status", "Статус"),
            ["scenario.status_active"]        = ("In progress", "В процессе"),
            ["scenario.status_won"]           = ("✅ Won!", "✅ Победа!"),
            ["scenario.status_lost"]          = ("❌ Lost", "❌ Поражение"),
            ["scenario.status_none"]          = ("—", "—"),
            ["scenario.time_remaining"]       = ("Time left", "Осталось времени"),
            ["scenario.elapsed"]              = ("Elapsed", "Прошло"),
            ["scenario.time_limit"]           = ("Time limit", "Срок"),
            ["scenario.days_n"]               = ("{0:F1} days", "{0:F1} дн."),
            ["scenario.goal"]                 = ("Goal", "Цель"),
            ["scenario.goal_survive"]         = ("Survive {0} days with net worth ≥ {1:C0}", "Продержись {0} дней с капиталом ≥ {1:C0}"),
            ["scenario.goal_networth"]        = ("Reach net worth of {0:C0} in {1} days", "Достигни капитала {0:C0} за {1} дн."),
            ["scenario.goal_money"]           = ("Reach cash balance of {0:C0} in {1} days", "Накопи наличных {0:C0} за {1} дн."),
            ["scenario.starting_money"]       = ("Starting cash", "Стартовые деньги"),
            ["scenario.starting_loan"]        = ("Starting debt", "Начальный долг"),
            ["scenario.current_networth"]     = ("Current net worth", "Текущий капитал"),
            ["scenario.progress"]             = ("Progress", "Прогресс"),
            ["scenario.warning_replaces"]     = ("Starting a scenario will change your money and may add a loan to your current profile.", "Запуск сценария изменит твои деньги и может добавить кредит к текущему профилю."),
            ["scenario.create_character"]     = ("Create a character before starting a scenario.", "Создай персонажа перед запуском сценария."),
            ["scenario.none_configured"]      = ("No scenarios configured. Check appsettings.json.", "Сценарии не настроены. Проверь appsettings.json."),
            ["scenario.started"]              = ("▶ Scenario started: {0}", "▶ Сценарий запущен: {0}"),
            ["scenario.abandoned"]            = ("Scenario abandoned.", "Сценарий прекращён."),
            ["scenario.goal_item_stock"]      = ("Accumulate {0} units of {1} in warehouse within {2} days", "Накопи {0} ед. товара '{1}' на складе за {2} дн."),

            // Two configured scenarios (names + descriptions)
            ["scenario.survive_debt.name"]    = ("Survive 7 days with $50K debt", "Выживи 7 дней с долгом $50K"),
            ["scenario.survive_debt.desc"]    = ("You're handed $50,000 of debt and one week on the clock. Keep net worth above zero until the loan matures.", "Тебе вешают долг $50,000 и дают неделю. Не уйди в минус по капиталу до срока."),
            ["scenario.millionaire.name"]     = ("Millionaire in 30 days", "Миллионер за 30 дней"),
            ["scenario.millionaire.desc"]     = ("Grow your net worth from pocket change to $1,000,000 within a month.", "Преврати стартовые гроши в капитал $1,000,000 за месяц."),
            ["scenario.sugar_king.name"]      = ("Sugar King", "Сахарный Король"),
            ["scenario.sugar_king.desc"]      = ("Amass 250,000 units of Sugar in your warehouse inventory within 20 days. Start with $5,000 and build your sugar empire!", "Накопи 250 000 единиц Сахара на своем складе за 20 дней. Начни с $5000 и построй свою сахарную империю!"),

            // Interactive Crisis Events
            ["event.robbery.title"]           = ("Office Robbery! 🚨", "Вооружённое ограбление! 🚨"),
            ["event.robbery.desc"]            = ("Armed thugs broke into your office! They demand a ransom, threatening to destroy files and equipment.", "Вооружённые бандиты ворвались в ваш офис! Они требуют выкуп, угрожая уничтожить оборудование и важные документы."),
            ["event.robbery.choice1"]         = ("Pay $15,000 Ransom", "Выплатить $15,000 выкупа"),
            ["event.robbery.choice1.desc"]    = ("The thugs took the money and left. Your office is intact, but your wallet is lighter.", "Бандиты забрали деньги и ушли. Офис цел, но кошелек заметно опустел."),
            ["event.robbery.choice2"]         = ("Call the Police (High Damage)", "Вызвать полицию (высокий ущерб)"),
            ["event.robbery.choice2.desc"]    = ("A shootout occurred! The bandits were arrested, but your office suffered $35,000 in damage, and the bad press hurt your reputation.", "Произошла перестрелка! Бандитов арестовали, но офис разгромлен (ущерб $35,000), а пресса раздула скандал, испортив вашу репутацию."),

            ["event.audit.title"]             = ("Tax Audit! 📄", "Налоговая проверка! 📄"),
            ["event.audit.desc"]              = ("State tax inspectors found discrepancies in your accounting books. You face heavy fines for tax evasion.", "Государственная налоговая инспекция обнаружила нестыковки в вашей отчетности. Вам грозит крупный штраф за неуплату налогов."),
            ["event.audit.choice1"]           = ("Hire Elite Attorney ($25,000)", "Нанять элитного адвоката ($25,000)"),
            ["event.audit.choice1.desc"]      = ("The attorney successfully challenged the audit! You paid $25,000, and your flawless compliance boosted your reputation.", "Адвокат успешно оспорил проверку! Вы заплатили ему $25,000, а безупречное решение дела подняло вашу репутацию."),
            ["event.audit.choice2"]           = ("Pay Full Penalty ($50,000)", "Выплатить штраф целиком ($50,000)"),
            ["event.audit.choice2.desc"]      = ("You paid the full $50,000 penalty. Your capital took a major hit, and your reputation suffered.", "Вы выплатили штраф в размере $50,000. Ваш капитал понес серьезные потери, а репутация пострадала."),

            ["event.fire.title"]              = ("Warehouse Fire! 🔥", "Пожар на складе! 🔥"),
            ["event.fire.desc"]               = ("A short circuit caused a fire in the next building, and it's quickly spreading to your warehouse!", "Короткое замыкание вызвало пожар в соседнем здании, и огонь быстро распространяется на ваш склад!"),
            ["event.fire.choice1"]            = ("Hire Private Firefighters ($8,000)", "Вызвать частных пожарных ($8,000)"),
            ["event.fire.choice1.desc"]       = ("Private firefighters arrived instantly and saved all your cargo! You paid $8,000, and gained public admiration.", "Частные пожарные прибыли мгновенно и спасли ваш груз! Вы заплатили $8,000, заслужив восхищение общественности."),
            ["event.fire.choice2"]            = ("Wait for City Department (Cargo Loss)", "Ждать городскую службу (утеря груза)"),
            ["event.fire.choice2.desc"]       = ("City fire trucks were stuck in traffic. Stored goods suffered $30,000 in damage, and the lack of safety measures hurt your reputation.", "Городские пожарные застряли в пробке. Складской груз пострадал на $30,000, а отсутствие мер безопасности подкосило вашу репутацию."),

            ["event.mafia.title"]             = ("Mafia Protection! 🕶️", "Визит мафии! 🕶️"),
            ["event.mafia.desc"]              = ("Local syndicate thugs pay a visit, demanding protection fees. Refusing could lead to sabotage.", "К вам пожаловали бойцы местного синдиката и вежливо предложили платить за «крышу». Отказ может привести к саботажу."),
            ["event.mafia.choice1"]           = ("Agree to Pay $12,000 Protection", "Согласиться платить $12,000 за «крышу»"),
            ["event.mafia.choice1.desc"]      = ("You paid $12,000. The thugs left, but word got out, harming your reputation in honest business circles.", "Вы заплатили $12,000. Бандиты ушли, но слухи об этом поползли, испортив вашу репутацию в кругах честного бизнеса."),
            ["event.mafia.choice2"]           = ("Hire Armed Security Team ($20,000)", "Нанять вооруженную охрану ($20,000)"),
            ["event.mafia.choice2.desc"]      = ("Armed security kicked the thugs out! You paid $20,000, but showing strength dramatically boosted your reputation.", "Вооруженная охрана жестко выставила вымогателей вон! Вы заплатили $20,000, но проявление силы резко подняло вашу репутацию."),
            ["event.mafia.choice3"]           = ("Refuse and Risk Sabotage", "Отказать и рискнуть саботажем"),
            ["event.mafia.choice3.desc"]      = ("You refused. That night, thugs sabotaged your warehouse! You suffered $40,000 in property damage, and your reputation dropped.", "Вы отказались. Ночью бандиты устроили саботаж! Вы понесли ущерб в $40,000, а ваша репутация упала."),

            ["event.flood.title"]             = ("Warehouse Flood! 🌊", "Наводнение на складе! 🌊"),
            ["event.flood.desc"]              = ("Heavy rainfall has caused local rivers to overflow. Water is rapidly entering your warehouse facility!", "Проливные дожди вызвали выход рек из берегов. Вода быстро затапливает помещение вашего склада!"),
            ["event.flood.choice1"]           = ("Deploy Sandbags & Pumps ($6,000)", "Установить мешки с песком и помпы ($6,000)"),
            ["event.flood.choice1.desc"]      = ("You successfully pumped out the water and sealed the entrance. All inventory was saved, and your proactive response was praised by the staff.", "Вы успешно откачали воду и загерметизировали вход. Весь груз был спасен, а персонал высоко оценил ваши быстрые действия."),
            ["event.flood.choice2"]           = ("Wait It Out (Severe Damage)", "Переждать наводнение (высокий ущерб)"),
            ["event.flood.choice2.desc"]      = ("Water flooded the lower racks, destroying a significant portion of your stored inventory. Suffer $25,000 in damage, and the lack of response hurt your reputation.", "Вода затопила нижние ярусы, уничтожив значительную часть хранящихся товаров. Ущерб составил $25,000, а бездействие ударило по репутации."),

            ["event.crisis.title"]            = ("Economic Crisis! 📉", "Экономический кризис! 📉"),
            ["event.crisis.desc"]             = ("A sudden downturn in the global economy triggers a credit squeeze and spikes operational overhead. You must act to stabilize your assets.", "Внезапный спад в мировой экономике сжимает кредитный рынок и резко повышает операционные расходы. Вам нужно принять меры для стабилизации."),
            ["event.crisis.choice1"]          = ("Restructure & Optimize ($12,000)", "Реструктуризация и оптимизация ($12,000)"),
            ["event.crisis.choice1.desc"]     = ("You paid $12,000 in legal and consulting fees to streamline operations. While your reputation took a minor hit due to downsizing, your assets remain secure.", "Вы заплатили $12,000 консалтинговым и юридическим фирмам для оптимизации процессов. Репутация немного снизилась из-за сокращений, но активы защищены."),
            ["event.crisis.choice2"]          = ("Absorb the Financial Hit", "Понести финансовый удар"),
            ["event.crisis.choice2.desc"]     = ("You attempted to endure without changes. The credit squeeze caused a major cash drain. Suffer $30,000 in operational losses, and market confidence in your business collapsed.", "Вы попытались переждать кризис без изменений. Дефицит ликвидности привел к резкому оттоку средств. Вы потеряли $30,000, а доверие рынка рухнуло."),

            ["event.cyber.title"]             = ("Cyber Attack! 💻", "Хакерская атака! 💻"),
            ["event.cyber.desc"]              = ("Anonymous hackers have encrypted your company's transaction databases with ransomware, demanding a massive cryptocurrency ransom!", "Анонимные хакеры зашифровали базы данных ваших сделок и требуют крупный выкуп в криптовалюте под угрозой полной потери данных!"),
            ["event.cyber.choice1"]           = ("Pay Ransom ($15,000)", "Выплатить выкуп ($15,000)"),
            ["event.cyber.choice1.desc"]      = ("You paid the bitcoin ransom. The hackers sent the decryption key, restoring operations, but giving in to cybercriminals hurt your professional reputation.", "Вы выплатили выкуп. Хакеры прислали ключ дешифрования и восстановили работу базы, но уступка киберпреступникам подкосила вашу профессиональную репутацию."),
            ["event.cyber.choice2"]           = ("Hire Cybersecurity Specialists ($20,000)", "Нанять специалистов по кибербезопасности ($20,000)"),
            ["event.cyber.choice2.desc"]      = ("Elite cybersecurity professionals decrypted the servers, patched the exploits, and reinforced your firewall. Your reputation in tech and safety soared!", "Элитные специалисты по безопасности расшифровали серверы, закрыли уязвимости и усилили брандмауэр. Ваша репутация надежной компании резко выросла!"),
            ["event.cyber.choice3"]           = ("Ignore and Rebuild (High Damage)", "Игнорировать и восстанавливать с нуля"),
            ["event.cyber.choice3.desc"]      = ("You refused to pay or hire support. Suffer $45,000 in lost client transactions, severe operational downtime, and a catastrophic drop in corporate reputation.", "Вы отказались платить или нанимать специалистов. Потери сделок клиентов, длительный простой и восстановление данных обошлись в $45,000, а репутация катастрофически упала."),

            // ----- Common -----
            ["common.close"]          = ("Close", "Закрыть"),
            ["common.confirm"]        = ("Confirm", "Подтвердить"),
            ["common.cancel"]         = ("Cancel", "Отмена"),
            ["common.yes"]            = ("Yes", "Да"),
            ["common.no"]             = ("No", "Нет"),
        };
    }
}
